from django.db import models

# Create your models here.
class DataCenters(models.Model):
	data_center_id_text = models.CharField(max_length=25)
	agency_data_center_id_text = models.CharField(max_length=25)
	legacy_data_center_id_text = models.CharField(max_length=25)
	record_status_text = models.CharField(max_length=25)
	record_validity_text = models.CharField(max_length=25)
	agency_abbreviation_text = models.CharField(max_length=6)
	component_text = models.CharField(max_length=6)
	office_name_text = models.CharField(max_length=25)
	data_center_name_text = models.CharField(max_length=25)
	published_name_text = models.CharField(max_length=25)
	core_classification_text = models.CharField(max_length=25)
	non_core_subcategory_text = models.CharField(max_length=40)
	city_text = models.CharField(max_length=40)
	state_text = models.CharField(max_length=2)
	province_text = models.CharField(max_length=25)
	zipcode_integer = models.IntegerField()
	country_text = models.CharField(max_length=40)
	ownership_type_text = models.CharField(max_length=25)
	colocation_provider_text = models.CharField(max_length=25)
	colocation_provider_type_text = models.CharField(max_length=25)
	government_wide_provider_text = models.CharField(max_length=25)
	providing_services_text = models.CharField(max_length=25)
	percent_services_paid_other_agencies_float = models.FloatField()
	other_agencies_serviced_text = models.CharField(max_length=25)
	data_center_tier_text = models.CharField(max_length=25)
	gross_floor_area_integer = models.IntegerField()
	total_customer_floor_area_integer = models.IntegerField()
	annual_cost_per_sqft_integer = models.IntegerField()
	fte_float = models.FloatField()
	fte_cost_float = models.FloatField()
	electricity_included_in_cost_text = models.CharField(max_length=25)
	electricity_metered_text = models.CharField(max_length=25)
	total_power_capactiy_float = models.FloatField()
	total_it_power_capacity_float = models.FloatField()
	avg_electricity_usage_float = models.FloatField()
	avg_it_electricity_usage_float = models.FloatField()
	cost_per_kwh_float = models.FloatField()
	rack_count_integer = models.IntegerField()
	total_ibm_mainframes_integer = models.IntegerField()
	total_other_mainframes_integer = models.IntegerField()
	total_window_servers_integer = models.IntegerField()
	total_unix_servers_integer = models.IntegerField()
	total_linux_servers_integer = models.IntegerField()
	total_hpc_cluster_nodes_integer = models.IntegerField()
	other_servers_integer = models.IntegerField()
	total_virtual_hosts_integer = models.IntegerField()
	total_virtual_os_integer = models.IntegerField()
	total_storage_float = models.FloatField()
	used_storage_float = models.FloatField()
	closing_stage_text = models.CharField(max_length=25)
	closing_fiscal_year_text = models.IntegerField()
	closing_quarter_text = models.CharField(max_length=25)
	real_property_disposition_text = models.CharField(max_length=25)
	real_property_disposition_date_text = models.CharField(max_length=25)
	total_floor_area_eliminated_repurposed_integer = models.IntegerField()
	total_decommissioned_physical_servers_integer = models.IntegerField()
	total_servers_moved_other_data_center_integer = models.IntegerField()
	overall_fte_reduction_float = models.FloatField()



	
	
	
	
	